# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = "ubuntu-docker"

  # Port forwarding dla WWW
  config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true

  # Host-only adapter (ten który stworzyłeś: 10.10.10.1)
  config.vm.network "private_network",
    ip: "10.10.10.10",
    name: "VirtualBox Host-Only Ethernet Adapter"

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "ubuntu-docker"
    vb.memory = 2048
    vb.cpus   = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release software-properties-common

    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    apt-get update -y
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
    usermod -aG docker vagrant
  SHELL
end
